
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.Map;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\007\000\002\003\005\000\002\003\005" +
    "\000\002\003\007\000\002\003\010\000\002\003\010\000" +
    "\002\003\010\000\002\003\005\000\002\017\006\000\002" +
    "\004\004\000\002\004\003\000\002\005\006\000\002\006" +
    "\003\000\002\006\003\000\002\006\003\000\002\006\003" +
    "\000\002\006\003\000\002\006\003\000\002\007\005\000" +
    "\002\007\003\000\002\010\005\000\002\011\003\000\002" +
    "\011\003\000\002\011\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\013\006\000\002\013\012" +
    "\000\002\020\003\000\002\020\003\000\002\012\005\000" +
    "\002\012\003\000\002\016\012\000\002\016\006\000\002" +
    "\021\005\000\002\021\003\000\002\022\005\000\002\014" +
    "\005\000\002\014\005\000\002\014\005\000\002\014\004" +
    "\000\002\014\005\000\002\015\003\000\002\015\003\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\015\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\163\000\022\004\007\005\014\006\015\007\005\014" +
    "\012\015\013\016\011\020\006\001\002\000\024\002\165" +
    "\004\007\005\014\006\015\007\005\014\012\015\013\016" +
    "\011\020\006\001\002\000\004\061\142\001\002\000\004" +
    "\061\140\001\002\000\004\061\130\001\002\000\024\002" +
    "\uffff\004\uffff\005\uffff\006\uffff\007\uffff\014\uffff\015\uffff" +
    "\016\uffff\020\uffff\001\002\000\004\061\063\001\002\000" +
    "\004\060\061\001\002\000\004\061\040\001\002\000\004" +
    "\061\036\001\002\000\004\061\016\001\002\000\004\043" +
    "\017\001\002\000\004\061\020\001\002\000\004\051\025" +
    "\001\002\000\006\044\ufff4\061\ufff4\001\002\000\006\044" +
    "\024\061\020\001\002\000\006\044\ufff5\061\ufff5\001\002" +
    "\000\024\002\ufffb\004\ufffb\005\ufffb\006\ufffb\007\ufffb\014" +
    "\ufffb\015\ufffb\016\ufffb\020\ufffb\001\002\000\016\021\026" +
    "\022\030\023\031\024\034\025\032\026\033\001\002\000" +
    "\004\052\ufff2\001\002\000\004\052\035\001\002\000\004" +
    "\052\ufff1\001\002\000\004\052\ufff0\001\002\000\004\052" +
    "\uffee\001\002\000\004\052\uffed\001\002\000\004\052\uffef" +
    "\001\002\000\006\044\ufff3\061\ufff3\001\002\000\004\052" +
    "\037\001\002\000\024\002\ufffd\004\ufffd\005\ufffd\006\ufffd" +
    "\007\ufffd\014\ufffd\015\ufffd\016\ufffd\020\ufffd\001\002\000" +
    "\004\043\041\001\002\000\004\061\042\001\002\000\004" +
    "\051\051\001\002\000\006\044\046\053\045\001\002\000" +
    "\006\044\uffeb\053\uffeb\001\002\000\004\061\042\001\002" +
    "\000\004\052\047\001\002\000\024\002\ufffa\004\ufffa\005" +
    "\ufffa\006\ufffa\007\ufffa\014\ufffa\015\ufffa\016\ufffa\020\ufffa" +
    "\001\002\000\006\044\uffec\053\uffec\001\002\000\016\027" +
    "\053\030\054\031\055\056\060\057\056\060\057\001\002" +
    "\000\006\044\uffea\053\uffea\001\002\000\016\040\uffe6\041" +
    "\uffe6\044\uffe6\046\uffe6\052\uffe6\053\uffe6\001\002\000\016" +
    "\040\uffe5\041\uffe5\044\uffe5\046\uffe5\052\uffe5\053\uffe5\001" +
    "\002\000\016\040\uffe4\041\uffe4\044\uffe4\046\uffe4\052\uffe4" +
    "\053\uffe4\001\002\000\016\040\uffe8\041\uffe8\044\uffe8\046" +
    "\uffe8\052\uffe8\053\uffe8\001\002\000\016\040\uffe7\041\uffe7" +
    "\044\uffe7\046\uffe7\052\uffe7\053\uffe7\001\002\000\016\040" +
    "\uffe9\041\uffe9\044\uffe9\046\uffe9\052\uffe9\053\uffe9\001\002" +
    "\000\004\052\062\001\002\000\024\002\ufffc\004\ufffc\005" +
    "\ufffc\006\ufffc\007\ufffc\014\ufffc\015\ufffc\016\ufffc\020\ufffc" +
    "\001\002\000\004\043\064\001\002\000\004\017\066\001" +
    "\002\000\004\044\126\001\002\000\004\051\067\001\002" +
    "\000\004\061\070\001\002\000\004\054\124\001\002\000" +
    "\006\052\uffda\053\uffda\001\002\000\006\052\074\053\073" +
    "\001\002\000\004\061\070\001\002\000\006\011\075\044" +
    "\uffdc\001\002\000\004\051\076\001\002\000\010\042\100" +
    "\045\102\061\077\001\002\000\016\032\115\033\117\034" +
    "\113\035\114\036\121\037\120\001\002\000\010\042\100" +
    "\045\102\061\077\001\002\000\010\040\104\041\106\052" +
    "\111\001\002\000\010\042\100\045\102\061\077\001\002" +
    "\000\010\040\104\041\106\046\105\001\002\000\010\042" +
    "\100\045\102\061\077\001\002\000\012\040\uffd4\041\uffd4" +
    "\046\uffd4\052\uffd4\001\002\000\010\042\100\045\102\061" +
    "\077\001\002\000\012\040\104\041\uffd6\046\uffd6\052\uffd6" +
    "\001\002\000\012\040\uffd7\041\uffd7\046\uffd7\052\uffd7\001" +
    "\002\000\004\044\uffdd\001\002\000\012\040\uffd5\041\uffd5" +
    "\046\uffd5\052\uffd5\001\002\000\016\027\uffd1\030\uffd1\031" +
    "\uffd1\056\uffd1\057\uffd1\060\uffd1\001\002\000\016\027\uffd0" +
    "\030\uffd0\031\uffd0\056\uffd0\057\uffd0\060\uffd0\001\002\000" +
    "\016\027\uffd3\030\uffd3\031\uffd3\056\uffd3\057\uffd3\060\uffd3" +
    "\001\002\000\016\027\053\030\054\031\055\056\060\057" +
    "\056\060\057\001\002\000\016\027\uffd2\030\uffd2\031\uffd2" +
    "\056\uffd2\057\uffd2\060\uffd2\001\002\000\016\027\uffce\030" +
    "\uffce\031\uffce\056\uffce\057\uffce\060\uffce\001\002\000\016" +
    "\027\uffcf\030\uffcf\031\uffcf\056\uffcf\057\uffcf\060\uffcf\001" +
    "\002\000\012\040\uffd8\041\uffd8\046\uffd8\052\uffd8\001\002" +
    "\000\006\052\uffdb\053\uffdb\001\002\000\016\027\053\030" +
    "\054\031\055\056\060\057\056\060\057\001\002\000\006" +
    "\052\uffd9\053\uffd9\001\002\000\004\052\127\001\002\000" +
    "\024\002\ufff8\004\ufff8\005\ufff8\006\ufff8\007\ufff8\014\ufff8" +
    "\015\ufff8\016\ufff8\020\ufff8\001\002\000\004\043\131\001" +
    "\002\000\004\012\132\001\002\000\004\013\135\001\002" +
    "\000\004\044\134\001\002\000\024\002\ufffe\004\ufffe\005" +
    "\ufffe\006\ufffe\007\ufffe\014\ufffe\015\ufffe\016\ufffe\020\ufffe" +
    "\001\002\000\004\060\136\001\002\000\004\052\137\001" +
    "\002\000\004\044\ufff6\001\002\000\004\052\141\001\002" +
    "\000\024\002\ufff7\004\ufff7\005\ufff7\006\ufff7\007\ufff7\014" +
    "\ufff7\015\ufff7\016\ufff7\020\ufff7\001\002\000\004\043\143" +
    "\001\002\000\004\010\145\001\002\000\004\044\162\001" +
    "\002\000\004\051\146\001\002\000\006\055\150\061\147" +
    "\001\002\000\006\052\uffde\053\uffde\001\002\000\004\052" +
    "\uffe0\001\002\000\006\052\uffe1\053\160\001\002\000\004" +
    "\052\153\001\002\000\006\011\154\044\uffe3\001\002\000" +
    "\004\051\155\001\002\000\010\042\100\045\102\061\077" +
    "\001\002\000\010\040\104\041\106\052\157\001\002\000" +
    "\004\044\uffe2\001\002\000\004\061\161\001\002\000\006" +
    "\052\uffdf\053\uffdf\001\002\000\004\052\163\001\002\000" +
    "\024\002\ufff9\004\ufff9\005\ufff9\006\ufff9\007\ufff9\014\ufff9" +
    "\015\ufff9\016\ufff9\020\ufff9\001\002\000\024\002\000\004" +
    "\000\005\000\006\000\007\000\014\000\015\000\016\000" +
    "\020\000\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\163\000\006\002\003\003\007\001\001\000\004\003" +
    "\163\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\004\021\005\020\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\022\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\006\026\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\007\042\010\043\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\010\047\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\051\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\016\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\021\071\022\070\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\022\122\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\100\001" +
    "\001\000\004\015\115\001\001\000\004\014\111\001\001" +
    "\000\002\001\001\000\004\014\102\001\001\000\002\001" +
    "\001\000\004\014\107\001\001\000\002\001\001\000\004" +
    "\014\106\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\011\121\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\011\124\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\017\132\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\143\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\012\150\020\151\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\155\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static BaseDatos baseActual = null;

    public void syntax_error(Symbol s){
        System.out.println(
            "Error sintactico en linea " + s.left +
            ", columna " + s.right +
            ", texto: " + s.value
        );
    }

    public void mostrarConsulta(String nombreTabla, ConsultaResultado consulta){
        if (baseActual == null) {
            System.out.println("Error: no hay una base de datos activa.");
            return;
        }

        Tabla tabla = baseActual.buscarTabla(nombreTabla);
        if (tabla == null) {
            System.out.println("Error: la tabla '" + nombreTabla + "' no existe.");
            return;
        }

        System.out.println("Resultado de consulta sobre tabla: " + nombreTabla);

        if (tabla.getRegistros().isEmpty()) {
            System.out.println("(sin registros)");
            return;
        }

        for (Registro registro : tabla.getRegistros()) {
            if (consulta.isTodosLosCampos()) {
                System.out.println(registro);
            } else {
                StringBuilder sb = new StringBuilder("{ ");
                boolean primero = true;

                for (String campo : consulta.getCampos()) {
                    Object valor = registro.getValor(campo);

                    if (!primero) {
                        sb.append(", ");
                    }

                    sb.append(campo).append(": ").append(valor);
                    primero = false;
                }

                sb.append(" }");
                System.out.println(sb.toString());
            }
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action_part00000000(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= programa sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // sentencia ::= DATABASE ID LLAVE_IZQ bloque_database LLAVE_DER 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    baseActual = new BaseDatos(n.toString(), r);
    System.out.println("Base de datos creada: " + n);
    System.out.println("Ruta JSON: " + r);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sentencia ::= USE ID PTCOMA 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    if (baseActual != null && baseActual.getNombre().equals(n.toString())) {
        System.out.println("Base de datos activa: " + n);
    } else {
        System.out.println("Advertencia: la base de datos '" + n + "' no existe o no coincide con la actual.");
    }

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentencia ::= EXPORT CADENA PTCOMA 
            {
              Object RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    System.out.println("Exportar a: " + r);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= TABLE ID LLAVE_IZQ lista_campos LLAVE_DER 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int lcleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		ArrayList lc = (ArrayList)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    if (baseActual != null) {
        Tabla tabla = new Tabla(n.toString());

        for (Object obj : lc) {
            tabla.agregarCampo((Campo)obj);
        }

        baseActual.agregarTabla(tabla);
        System.out.println("Tabla creada: " + n);
    } else {
        System.out.println("Error: no hay una base de datos activa para crear la tabla " + n);
    }

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= ADD ID LLAVE_IZQ lista_asignaciones LLAVE_DER PTCOMA 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;
		int laleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		ArrayList la = (ArrayList)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		
    if (baseActual != null) {
        Tabla tabla = baseActual.buscarTabla(n.toString());

        if (tabla != null) {
            Registro registro = new Registro();

            for (Object obj : la) {
                AsignacionDato ad = (AsignacionDato)obj;
                registro.agregarValor(ad.getCampo(), ad.getValor());
            }

            tabla.agregarRegistro(registro);
            System.out.println("Registro agregado en tabla: " + n);
        } else {
            System.out.println("Error: la tabla '" + n + "' no existe.");
        }
    } else {
        System.out.println("Error: no hay una base de datos activa.");
    }

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= READ ID LLAVE_IZQ bloque_read LLAVE_DER PTCOMA 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;
		int brleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int brright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		ConsultaResultado br = (ConsultaResultado)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		
    mostrarConsulta(n.toString(), br);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= UPDATE ID LLAVE_IZQ bloque_update LLAVE_DER PTCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= CLEAR ID PTCOMA 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    if (baseActual != null) {
        Tabla tabla = baseActual.buscarTabla(n.toString());
        if (tabla != null) {
            tabla.limpiarRegistros();
            System.out.println("Tabla limpiada: " + n);
        } else {
            System.out.println("Error: la tabla '" + n + "' no existe.");
        }
    } else {
        System.out.println("Error: no hay una base de datos activa.");
    }

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bloque_database ::= STORE AT CADENA PTCOMA 
            {
              String RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    RESULT = r.toString().replace("\"", "");

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque_database",13, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_campos ::= lista_campos campo 
            {
              ArrayList RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		ArrayList lc = (ArrayList)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Campo c = (Campo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    lc.add(c);
    RESULT = lc;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_campos",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_campos ::= campo 
            {
              ArrayList RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Campo c = (Campo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    ArrayList lista = new ArrayList();
    lista.add(c);
    RESULT = lista;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_campos",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // campo ::= ID DOS_PUNTOS tipo PTCOMA 
            {
              Campo RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    RESULT = new Campo(n.toString(), t);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("campo",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // tipo ::= TINT 
            {
              String RESULT =null;
		
    RESULT = "int";

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // tipo ::= TFLOAT 
            {
              String RESULT =null;
		
    RESULT = "float";

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= TBOOL 
            {
              String RESULT =null;
		
    RESULT = "bool";

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo ::= TSTRING 
            {
              String RESULT =null;
		
    RESULT = "string";

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo ::= TARRAY 
            {
              String RESULT =null;
		
    RESULT = "array";

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= TOBJECT 
            {
              String RESULT =null;
		
    RESULT = "object";

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_asignaciones ::= lista_asignaciones COMA asignacion 
            {
              ArrayList RESULT =null;
		int laleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		ArrayList la = (ArrayList)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		AsignacionDato a = (AsignacionDato)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    la.add(a);
    RESULT = la;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_asignaciones",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lista_asignaciones ::= asignacion 
            {
              ArrayList RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		AsignacionDato a = (AsignacionDato)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    ArrayList lista = new ArrayList();
    lista.add(a);
    RESULT = lista;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_asignaciones",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // asignacion ::= ID DOS_PUNTOS valor 
            {
              AsignacionDato RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    RESULT = new AsignacionDato(n.toString(), v);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("asignacion",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // valor ::= ENTERO 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    RESULT = Integer.parseInt(e.toString());

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // valor ::= DECIMAL 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    RESULT = Double.parseDouble(d.toString());

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // valor ::= CADENA 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    RESULT = c.toString().substring(1, c.toString().length() - 1);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // valor ::= TRUE 
            {
              Object RESULT =null;
		
    RESULT = true;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // valor ::= FALSE 
            {
              Object RESULT =null;
		
    RESULT = false;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // valor ::= NULL 
            {
              Object RESULT =null;
		
    RESULT = null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // bloque_read ::= FIELDS DOS_PUNTOS seleccion_campos PTCOMA 
            {
              ConsultaResultado RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		ConsultaResultado s = (ConsultaResultado)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
    RESULT = s;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque_read",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // bloque_read ::= FIELDS DOS_PUNTOS seleccion_campos PTCOMA FILTER DOS_PUNTOS condicion PTCOMA 
            {
              ConsultaResultado RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).right;
		ConsultaResultado s = (ConsultaResultado)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).value;
		
    System.out.println("Aviso: filter reconocido sintacticamente, pero aun no aplicado semantica.");
    RESULT = s;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque_read",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // seleccion_campos ::= lista_ids 
            {
              ConsultaResultado RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    ConsultaResultado cr = new ConsultaResultado();
    cr.setCampos(l);
    cr.setTodosLosCampos(false);
    RESULT = cr;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seleccion_campos",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // seleccion_campos ::= ASTERISCO 
            {
              ConsultaResultado RESULT =null;
		
    ConsultaResultado cr = new ConsultaResultado();
    cr.setTodosLosCampos(true);
    RESULT = cr;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("seleccion_campos",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_ids ::= lista_ids COMA ID 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    l.add(n.toString());
    RESULT = l;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_ids",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_ids ::= ID 
            {
              ArrayList RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    ArrayList lista = new ArrayList();
    lista.add(n.toString());
    RESULT = lista;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_ids",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // bloque_update ::= SET DOS_PUNTOS lista_set PTCOMA FILTER DOS_PUNTOS condicion PTCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque_update",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // bloque_update ::= SET DOS_PUNTOS lista_set PTCOMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("bloque_update",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_set ::= lista_set COMA asignacion_set 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		AsignacionDato a = (AsignacionDato)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    l.add(a);
    RESULT = l;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_set",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // lista_set ::= asignacion_set 
            {
              ArrayList RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		AsignacionDato a = (AsignacionDato)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    ArrayList lista = new ArrayList();
    lista.add(a);
    RESULT = lista;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("lista_set",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // asignacion_set ::= ID IGUAL valor 
            {
              AsignacionDato RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    RESULT = new AsignacionDato(n.toString(), v);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("asignacion_set",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // condicion ::= ID operador_relacional valor 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // condicion ::= condicion AND condicion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // condicion ::= condicion OR condicion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // condicion ::= NOT condicion 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // condicion ::= PAR_IZQ condicion PAR_DER 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("condicion",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // operador_relacional ::= IGUALIGUAL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("operador_relacional",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // operador_relacional ::= DIFERENTE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("operador_relacional",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // operador_relacional ::= MAYORIGUAL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("operador_relacional",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // operador_relacional ::= MENORIGUAL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("operador_relacional",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // operador_relacional ::= MAYOR 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("operador_relacional",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // operador_relacional ::= MENOR 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("operador_relacional",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico$do_action_part00000000(
                               CUP$Sintactico$act_num,
                               CUP$Sintactico$parser,
                               CUP$Sintactico$stack,
                               CUP$Sintactico$top);
    }
}

}
