
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 36;
  public static final int TSTRING = 18;
  public static final int STORE = 8;
  public static final int ENTERO = 44;
  public static final int TFLOAT = 16;
  public static final int DIFERENTE = 25;
  public static final int DOS_PUNTOS = 39;
  public static final int FILTER = 7;
  public static final int ASTERISCO = 43;
  public static final int COR_DER = 38;
  public static final int UPDATE = 12;
  public static final int LLAVE_IZQ = 33;
  public static final int NOT = 32;
  public static final int MENORIGUAL = 27;
  public static final int AND = 30;
  public static final int IGUAL = 42;
  public static final int USE = 3;
  public static final int OR = 31;
  public static final int TBOOL = 17;
  public static final int ID = 47;
  public static final int MAYORIGUAL = 26;
  public static final int DECIMAL = 45;
  public static final int EOF = 0;
  public static final int TABLE = 4;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int COMA = 41;
  public static final int TOBJECT = 20;
  public static final int CADENA = 46;
  public static final int EXPORT = 10;
  public static final int ADD = 11;
  public static final int NULL = 23;
  public static final int MENOR = 29;
  public static final int FIELDS = 6;
  public static final int TARRAY = 19;
  public static final int PAR_IZQ = 35;
  public static final int MAYOR = 28;
  public static final int TINT = 15;
  public static final int LLAVE_DER = 34;
  public static final int READ = 5;
  public static final int IGUALIGUAL = 24;
  public static final int CLEAR = 14;
  public static final int COR_IZQ = 37;
  public static final int DATABASE = 2;
  public static final int PTCOMA = 40;
  public static final int AT = 9;
  public static final int FALSE = 22;
  public static final int SET = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DATABASE",
  "USE",
  "TABLE",
  "READ",
  "FIELDS",
  "FILTER",
  "STORE",
  "AT",
  "EXPORT",
  "ADD",
  "UPDATE",
  "SET",
  "CLEAR",
  "TINT",
  "TFLOAT",
  "TBOOL",
  "TSTRING",
  "TARRAY",
  "TOBJECT",
  "TRUE",
  "FALSE",
  "NULL",
  "IGUALIGUAL",
  "DIFERENTE",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MAYOR",
  "MENOR",
  "AND",
  "OR",
  "NOT",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "DOS_PUNTOS",
  "PTCOMA",
  "COMA",
  "IGUAL",
  "ASTERISCO",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "ID"
  };
}

